[project]
authors = ["Ryan Oates <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "nova-act"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.9,<3.13"
pip = ">=25.0.1,<26"
max = ">=25.3.0.dev2025040405,<26"
pandas = ">=2.2.3,<3"
numpy = ">=1.26.4,<2"
