[build-system]
requires = [
  "build",
  "setuptools>=42",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "nova-act"
description = "A Python SDK for Amazon Nova Act."
dynamic = ["dependencies", "version"]
requires-python = ">=3.12"
authors = [
  {name = "Ryan Oates", email = "ryanoatsie@outlook.com"},
]
license = {text = "Apache-2.0"}
readme = "README.md"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = [
  "build",
  "pytest",
  "ruff",
  "mypy",
  "setuptools",
  "twine",
  "wheel",
]

[tool.setuptools]
packages = ["nova_act"]

[tool.setuptools.dynamic]
version = {attr = "nova_act.__version__"}
dependencies = {file = "requirements.txt"}

[tool.setuptools.package-data]
nova_act = ["artifacts/**/*", "artifacts/*"]

[tool.pixi.project]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
nova-act = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.tasks]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[tool.ruff]
line-length = 100
target-version = "py312"
exclude = ["build/"]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
exclude = ["build/"]
