[build-system]
requires = [
  "build",
  "setuptools",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "nova-act"
description = "A Python SDK for Amazon Nova Act."
dynamic = ["dependencies", "version"]
requires-python = ">=3.10"
authors = [
  {name = "Amazon Nova Act", email="nova-act@amazon.com"},
]
license = "Apache-2.0"
readme = "README.md"

[project.optional-dependencies]
dev = [
  "build",
  "setuptools",
  "twine",
  "wheel",
]

[tool.setuptools.dynamic]
version = {attr = "nova_act.__version__.VERSION"}
dependencies = {file = "requirements.txt"}

[tool.setuptools.package-data]
nova_act = ["artifacts/**/*", "artifacts/*"]

[tool.pixi.project]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
nova-act = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.tasks]

[tool.pixi.dependencies]
pip = ">=25.1.1,<26"
scikit-learn = ">=1.6.1,<2"
numpy = ">=2.2.5,<3"
pandas = ">=2.2.3,<3"
anthropic = ">=0.50.0,<0.51"
openai = ">=1.77.0,<2"
