[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nova-act"
version = "0.1.0"
description = "NovaAct Python Package"
requires-python = ">=3.8"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-asyncio"
]

[tool.hatch.build]
packages = ["src"]